- name: Lab
  width: wide
  desktop-navigation-width: wide
  columns:
    - size: full
      widgets:
        - type: server-stats
          title: Dashboard Servers
          servers:
            - type: local
              name: Raspberry Pi
        - type: custom-api
          title: Media Servers
          css-class: widget-type-server-stats-custom
          url: "http://10.0.0.90:27974/?token=2uc3KLKIEi48SMwGeaRd6g5BB1X9b0lYptGNuxwr6Go9q0d7GV"
          cache: 1m
          template: |
            <div class="server">
              <div class="server-info">
                <div class="server-details">
                  <div class="server-name color-highlight size-h3">Plex Server</div>
                  <div>live API stats</div>
                </div>
                <div class="shrink-0">
                  <svg class="server-icon" stroke="var(--color-positive)" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 17.25v-.228a4.5 4.5 0 0 0-.12-1.03l-2.268-9.64a3.375 3.375 0 0 0-3.285-2.602H7.923a3.375 3.375 0 0 0-3.285 2.602l-2.268 9.64a4.5 4.5 0 0 0-.12 1.03v.228m19.5 0a3 3 0 0 1-3 3H5.25a3 3 0 0 1-3-3m19.5 0a3 3 0 0 0-3-3H5.25a3 3 0 0 0-3 3m16.5 0h.008v.008h-.008v-.008Zm-3 0h.008v.008h-.008v-.008Z" />
                  </svg>
                </div>
              </div>
              <div class="server-stats">
                <div class="flex-1">
                  <div class="flex items-end size-h5">
                    <div>CPU</div>
                    <div class="color-highlight margin-left-auto text-very-compact">{{ .JSON.Float "cpu" }} <span class="color-base">%</span></div>
                  </div>
                  <div class="progress-bar progress-bar-combined">
                    <div class="progress-value{{ if ge (.JSON.Float "cpu") 85.0 }} progress-value-notice{{ end }}" style="--percent: {{ .JSON.Float "cpu" }}"></div>
                  </div>
                </div>
                <div class="flex-1">
                  <div class="flex justify-between items-end size-h5">
                    <div>RAM</div>
                    <div class="color-highlight text-very-compact">{{ .JSON.Float "memory.usedPercent" }} <span class="color-base">%</span></div>
                  </div>
                  <div data-popover-type="html">
                    <div data-popover-html>
                      <div class="flex">
                        <div class="size-h5">RAM</div>
                        <div class="value-separator"></div>
                        <div class="color-highlight text-very-compact">{{ .JSON.Float "memory.usedGB" }} <span class="color-base size-h5">GB /</span> {{ .JSON.Float "memory.totalGB" }} <span class="color-base size-h5">GB</span></div>
                      </div>
                    </div>
                    <div class="progress-bar progress-bar-combined">
                      <div class="progress-value{{ if ge (.JSON.Float "memory.usedPercent") 85.0 }} progress-value-notice{{ end }}" style="--percent: {{ .JSON.Float "memory.usedPercent" }}"></div>
                    </div>
                  </div>
                </div>
                <div class="flex-1">
                  <div class="flex justify-between items-end size-h5">
                    <div>DISK</div>
                    <div class="color-highlight text-very-compact">{{ .JSON.Float "disks.0.usedPercent" }} <span class="color-base">%</span></div>
                  </div>
                  <div data-popover-type="html">
                    <div data-popover-html>
                      <ul class="list list-gap-2">
                        {{ range .JSON.Array "disks" }}
                        <li class="flex">
                          <div class="size-h5">{{ .String "name" }} {{ .String "label" }}</div>
                          <div class="value-separator"></div>
                          <div class="color-highlight text-very-compact">{{ .Float "usedGB" }} <span class="color-base size-h5">GB /</span> {{ .Float "sizeGB" }} <span class="color-base size-h5">GB</span></div>
                        </li>
                        {{ end }}
                      </ul>
                    </div>
                    <div class="progress-bar progress-bar-combined">
                      <div class="progress-value{{ if ge (.JSON.Float "disks.0.usedPercent") 85.0 }} progress-value-notice{{ end }}" style="--percent: {{ .JSON.Float "disks.0.usedPercent" }}"></div>
                      {{ if ge (len (.JSON.Array "disks")) 2 }}
                      <div class="progress-value{{ if ge (.JSON.Float "disks.1.usedPercent") 85.0 }} progress-value-notice{{ end }}" style="--percent: {{ .JSON.Float "disks.1.usedPercent" }}"></div>
                      {{ end }}
                    </div>
                  </div>
                </div>
              </div>
            </div>
        - type: server-stats
          title: NAS Drives
          servers:
            - type: remote
              name: File Server
              url: http://10.0.0.13:27973
            - type: remote
              name: Media Server
              url: http://10.0.0.110:27974

        - type: custom-api
          title: Cloudflared Tunnels
          css-class: "widget-type-cloudflared"
          url: https://api.cloudflare.com/client/v4/accounts/c4d9e300ef73663d14b9aff33009569a/cfd_tunnel/c587464d-7e2d-4fe2-b8d2-8960283c1f48/configurations
          headers:
            Authorization: Bearer NdfjpEAOSB8z8B_Qn1RZumgTiVyG7IvvaHNSNvte
          template: |
            {{ $domain_name := ".example.com" }}  {{/* Set your domain name */}}

            <style>
              .widget-type-cloudflared li {
                margin-top: var(--list-half-gap); 
                border-top: 1px solid var(--color-separator);
                padding-top: var(--list-half-gap);
              }
            </style>
            <ul class="dynamic-columns list-gap-15 list-with-separator">
            {{ range .JSON.Array "result.config.ingress" }}
              {{ if (.String "hostname") }}
              <li class="flex items-center gap-20">
                  <div class="shrink-0">
                      <img class="docker-container-icon" src="https://developers.cloudflare.com/logo.svg" alt="" loading="lazy">
                  </div>
                  <div class="min-width-0 grow">
                    <a href='https://{{ .String "hostname" }}' class="color-highlight size-title-dynamic block text-truncate" target="_blank" rel="noreferrer">{{ .String "hostname" | trimSuffix $domain_name }}</a>
                    {{ if (.String "service") }}
                    <div class="flex items-center gap-10" style="margin-bottom: 5px">
                      <div class="text-left">
                        <img src="assets/arrow.png" style="width: auto; height: 20px; margin-left: 0px; margin-top: -4px;">
                      </div>
                      <div class="size-h6 flex-1 text-left">
                        <a href='{{ .String "service" | replaceAll "localhost" "192.168.0.150" }}' target="_blank" rel="noreferrer">{{ .String "service" }}</a>
                      </div>
                    </div>
                    {{ end}}
                  </div>
              </li>
              {{ end }}
            {{ end }}
            </ul>

        - type: group
          widgets:
          - type: reddit
            subreddit: selfhosted
            show-thumbnails: true
            limit: 10
            collapse-after: 10
          - type: reddit
            subreddit: arduino
            show-thumbnails: true
            limit: 10
            collapse-after: 10
          - type: reddit
            subreddit: cybersecurity
            show-thumbnails: true
            limit: 10
            collapse-after: 10
          - type: reddit
            subreddit: HowToHack
            show-thumbnails: true 
            limit: 10     
            collapse-after: 10      
          - type: reddit
            subreddit: RASPBERRY_PI_PROJECTS
            show-thumbnails: true
            limit: 10
            collapse-after: 10
          - type: reddit
            subreddit: ArtificialInteligence
            show-thumbnails: true               

