- name: Links
  width: wide
  desktop-navigation-width: wide
  columns:
    - size: full
      widgets:
        - type: bookmarks
          css-class: bookmarks-layout-rows
          groups:
            - title: Blake's School
              links:
                - title: John Swett Lunch Menu
                  url: https://martinezusd.nutrislice.com/menu/john-swett-elementary/lunch/2025-05-10
                  icon: /assets/jsrr.webp
                - title: MUSD Aeries
                  url: https://martinezusd.aeries.net/student/LoginParent.aspx              
                  icon: /assets/aeries.png          
            - title: Media Admin Panels
              links:
                - title: Local Plex
                  url: http://10.0.0.90:32400/web/
                  icon: /assets/plex.png
                - title: Sonarr
                  url: http://10.0.0.90:8989/
                  icon: /assets/sonarr.svg
                - title: Radarr
                  url: http://10.0.0.90:7878/
                  icon: /assets/radarr.png
                - title: SABnzbd
                  url: http://10.0.0.90:8081/
                  icon: /assets/sab.png
                - title: Requestrr
                  url: http://10.0.0.90:4545/
                  icon: /assets/requestrr.png
            - title: Hosted Services
              links:
                - title: Kuma
                  url: http://10.0.0.46:3001/
                  icon: /assets/kuma.png
                - title: Archv
                  url: http://10.0.0.46:4000
                  icon: /assets/archv.png
                - title: Archv - Admin Panel
                  url: http://10.0.0.46:4001
                  icon: /assets/archv.png
                - title: Arctrak
                  url: http://10.0.0.46:4002
                  icon: /assets/arc.png           
            - title: Tech Tools
              links:
                - title: Cyber Chef
                  url: https://gchq.github.io/CyberChef/#recipe=To_Base85('!-u',true)To_Hex('Space',0)Vigen%C3%A8re_Encode('diglette')&input=aHR0cHM6Ly90aW55dXJsLmNvbS80bjUzbnNydQ
                  icon: /assets/chef.png
                - title: MXToolBox
                  url: https://mxtoolbox.com/Public/Tools/EmailHeaders.aspx?huid=b950bf90-1ff6-46ae-927a-3fc9aa75c83f      
                  icon: /assets/mx.png   
            - title: Interactive Game Maps
              links:
                - title: Windrose
                  url: https://windrose.tools/map?layout=cfe2aa209f136f93
                  icon: /assets/windrose.png
                - title: Valheim
                  url: https://valheim-map.world/index.html
                  icon: /assets/valheim.jpg
                - title: Arc Raiders
                  url: https://mapgenie.io/arc-raiders
                  icon: /assets/arcraiders.png
                - title: DayZ
                  url: https://www.izurvive.com/
                  icon: /assets/dayz.ico
                - title: Icarus
                  url: https://mapgenie.io/icarus/maps/icarus
                  icon: /assets/icarus.ico                  
            - title: Unreal Creators Youtube
              links:
                - title: Reids Channel
                  url: https://www.youtube.com/@ReidsChannel
                  icon: /assets/reids.jpg
                - title: Ryan Laley
                  url: https://www.youtube.com/@RyanLaley
                  icon: /assets/ryan.jpg
                - title: Pitchfork Academy
                  url: https://www.youtube.com/@PitchforkAcademy
                  icon: /assets/pitchfork.jpg
                - title: Gorka Games
                  url: https://www.youtube.com/@GorkaGames
                  icon: /assets/gorka.jpg
                - title: Zero2GameDev
                  url: https://www.youtube.com/@Zero2GameDev0
                  icon: /assets/zero.jpg                      