- name: Projects
  width: wide
  desktop-navigation-width: wide
  columns:
    - size: small
      widgets:
        - type: bookmarks
          groups:
            - title: Unreal Creators Youtube
              links:
                - title: Reids Channel
                  url: https://www.youtube.com/@ReidsChannel
                  icon: /assets/reids.jpg
                - title: Ryan Laley
                  url: https://www.youtube.com/@RyanLaley
                  icon: /assets/ryan.jpg
                - title: Pitchfork Academy
                  url: https://www.youtube.com/@PitchforkAcademy
                  icon: /assets/pitchfork.jpg
                - title: Gorka Games
                  url: https://www.youtube.com/@GorkaGames
                  icon: /assets/gorka.jpg
                - title: Zero2GameDev
                  url: https://www.youtube.com/@Zero2GameDev0
                  icon: /assets/zero.jpg                  

    - size: full
      widgets:
        - type: repository
          repository: johnt0991/ARCHV
          title: ARCHV.online
          pull-requests-limit: 5
          token: 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
          issues-limit: 3
          commits-limit: 3

        - type: repository
          title: The Valley
          token: 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
          repository: johnt0991/TheValley
          pull-requests-limit: 5
          issues-limit: 3
          commits-limit: 3
          
        - type: repository
          title: CrawlSpace
          repository: johnt0991/CrawlSpace
          pull-requests-limit: 5
          issues-limit: 3
          commits-limit: 3